
(function(){
 const $=s=>document.querySelector(s),clone=v=>JSON.parse(JSON.stringify(v));let introDone=false,partyTimer=null,audioCtx=null,partyNodes=[];
 function renderTicker(){const items=(FSRP_STORE.get().ticker||[]).filter(x=>x.enabled!==false);const html=items.map(x=>`<span class="ticker-item">${x.text}</span>`).join('');$('#ticker-track').innerHTML=html+html}
 function showTakeover(){const t=FSRP_STORE.get().takeover||{};if(!t.enabled||!t.id||localStorage.getItem(`fsrpTakeoverSeen:${t.id}`))return;$('#takeover-title').textContent=t.title;$('#takeover-message').textContent=t.message;$('#takeover-button').textContent=t.buttonLabel||'View Update';$('#takeover-button').href=t.buttonUrl||'#community';$('#announcement-takeover').hidden=false;setTimeout(closeTakeover,3000)}
 function closeTakeover(){const t=FSRP_STORE.get().takeover||{};if(t.id)localStorage.setItem(`fsrpTakeoverSeen:${t.id}`,'1');$('#announcement-takeover').hidden=true}
 function setupIntro(){const s=FSRP_STORE.get(),cfg=s.experience||{},root=$('#opening-sequence');if(!cfg.introEnabled||(!cfg.introEveryRefresh&&sessionStorage.getItem('fsrpIntroSeen'))){root.hidden=true;setTimeout(showTakeover,500);return}root.hidden=false;document.body.style.overflow='hidden';const media=$('#intro-media');media.innerHTML='';if(cfg.introMediaUrl&&cfg.introMediaType==='video'){const v=document.createElement('video');v.src=cfg.introMediaUrl;v.autoplay=true;v.muted=true;v.loop=true;v.playsInline=true;media.append(v)}else if(cfg.introMediaUrl&&cfg.introMediaType==='image'){const img=new Image();img.src=cfg.introMediaUrl;img.alt='FSRP intro media';media.append(img)}setTimeout(beginLoader,3600)}
 function beginLoader(){if(introDone)return;introDone=true;const root=$('#opening-sequence');root.classList.add('falling');setTimeout(()=>{root.classList.add('loading');const bar=$('#intro-progress-bar'),num=$('#intro-progress-number'),msg=$('#intro-loader-message');requestAnimationFrame(()=>bar.style.width='100%');[[300,18,'Connecting to roleplay services'],[850,42,'Loading departments and staff'],[1450,68,'Opening live command systems'],[2100,89,'Preparing the FSRP CAD'],[2600,100,'Welcome to Florida State Roleplay']].forEach(([d,p,m])=>setTimeout(()=>{num.textContent=p+'%';msg.textContent=m},d));setTimeout(closeIntro,2950)},1050)}
 function closeIntro(){const root=$('#opening-sequence');root.style.opacity='0';root.style.transition='.7s';document.body.style.overflow='';sessionStorage.setItem('fsrpIntroSeen','1');setTimeout(()=>root.hidden=true,720);setTimeout(showTakeover,820)}
 function clock(){const n=new Date();$('#device-time').textContent=n.toLocaleTimeString([],{hour:'numeric',minute:'2-digit',second:'2-digit'});$('#device-date').textContent=n.toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})+' · '+(Intl.DateTimeFormat().resolvedOptions().timeZone||'Local')}
 let logoClicks=0,logoClickTimer;
 function logoClick(){logoClicks++;clearTimeout(logoClickTimer);if(logoClicks>=4){logoClicks=0;startParty();return}logoClickTimer=setTimeout(()=>{if(logoClicks===2)$('#lwktimmy-easter').hidden=false;logoClicks=0},650)}
 function startParty(){if(partyTimer)return;const root=$('#party-mode');root.hidden=false;let left=60;$('#party-countdown').textContent=left;makeMusic();makeConfetti();partyTimer=setInterval(()=>{left--;$('#party-countdown').textContent=left;if(left<=0)stopParty()},1000)}
 function makeConfetti(){const root=$('#party-confetti');root.innerHTML='';for(let i=0;i<180;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left=Math.random()*100+'%';p.style.setProperty('--hue',Math.floor(Math.random()*360));p.style.setProperty('--duration',(3+Math.random()*6)+'s');p.style.setProperty('--drift',(-100+Math.random()*200)+'px');p.style.animationDelay=(Math.random()*5)+'s';root.append(p)}}
 function makeMusic(){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();const master=audioCtx.createGain();master.gain.value=.11;master.connect(audioCtx.destination);partyNodes.push(master);const notes=[110,146.83,164.81,220,196,146.83,130.81,164.81];let step=0;const play=()=>{if(!audioCtx)return;const now=audioCtx.currentTime,o=audioCtx.createOscillator(),g=audioCtx.createGain(),bass=audioCtx.createOscillator(),bg=audioCtx.createGain();o.type='sawtooth';o.frequency.value=notes[step%notes.length]*2;bass.type='square';bass.frequency.value=notes[step%notes.length]/2;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.12,now+.015);g.gain.exponentialRampToValueAtTime(.0001,now+.22);bg.gain.setValueAtTime(.0001,now);bg.gain.exponentialRampToValueAtTime(.08,now+.01);bg.gain.exponentialRampToValueAtTime(.0001,now+.12);o.connect(g).connect(master);bass.connect(bg).connect(master);o.start(now);bass.start(now);o.stop(now+.24);bass.stop(now+.14);step++};play();partyNodes.push(setInterval(play,250))}catch{}}
 function stopParty(){clearInterval(partyTimer);partyTimer=null;partyNodes.forEach(n=>typeof n==='number'?clearInterval(n):null);partyNodes=[];if(audioCtx){audioCtx.close();audioCtx=null}$('#party-mode').hidden=true;$('#party-confetti').innerHTML=''}
 document.addEventListener('click',e=>{if(e.target.closest('#takeover-close'))closeTakeover();if(e.target.closest('[data-logo-easter],.brand img,.footer-brand img'))logoClick();if(e.target.closest('[data-close-easter]'))$('#lwktimmy-easter').hidden=true;if(e.target.closest('#party-stop'))stopParty();if(e.target.closest('#intro-enter'))beginLoader()});document.addEventListener('fsrp:state',()=>{renderTicker()});document.addEventListener('DOMContentLoaded',()=>{renderTicker();clock();setInterval(clock,1000);setupIntro()})
})();
