
(function(){
 let token='',role='preview';const clone=v=>JSON.parse(JSON.stringify(v));
 const getPath=(o,p)=>p.split('.').reduce((a,k)=>a?.[k],o);const setPath=(o,p,v)=>{const a=p.split('.');let c=o;a.slice(0,-1).forEach(k=>c=c[k]??(c[k]={}));c[a.at(-1)]=v};
 function toast(m){const t=document.getElementById('toast');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
 function unlock(mode='preview'){role=mode;document.getElementById('manager-login').hidden=true;document.getElementById('manager-app').hidden=false;document.getElementById('manager-role-label').textContent=mode==='preview'?'Local Preview':'Authorized Manager';document.getElementById('manager-mode-label').textContent=mode;document.getElementById('manager-connection-badge').innerHTML='<i class="status-dot online"></i>Connected';bindFields();renderEditors()}
 async function login(){const code=document.getElementById('manager-passcode').value;const msg=document.getElementById('manager-login-message');msg.textContent='Checking authorization…';try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({passcode:code})});const d=await r.json();if(!r.ok)throw Error(d.error||'Authorization failed');token=d.token||code;unlock(d.role||'manager');msg.textContent=''}catch(e){msg.textContent=e.message}}
 function bindFields(){const s=FSRP_STORE.get();document.querySelectorAll('[data-bind]').forEach(el=>{const v=getPath(s,el.dataset.bind);if(el.type==='checkbox')el.checked=!!v;else if(el.tagName==='SELECT'&&typeof v==='boolean')el.value=String(v);else el.value=v??'';el.onchange=()=>{let val=el.type==='checkbox'?el.checked:el.value;if(el.tagName==='SELECT'&&(val==='true'||val==='false'))val=val==='true';const next=clone(FSRP_STORE.get());setPath(next,el.dataset.bind,val);FSRP_STORE.set(next);document.getElementById('save-state').textContent='Preview has unpublished changes.'}})}
 const schemas={announcements:['title','body','date','category'],events:['title','description','date'],timeline:['date','title','description'],gallery:['title','type','url'],departments:['name','short','category','description','status'],ranks:['id','name'],staff:['name','rank','title','initials','status'],systems:['title','description'],joinSteps:['title','description'],faqs:['question','answer'],rules:['title','items'],marketplace:['title','description','url'],support:['title','description','url'],ticker:['text','enabled']};
 const editorIds={announcements:'announcement-editor',events:'event-editor',timeline:'timeline-editor',gallery:'gallery-editor',departments:'department-editor',ranks:'rank-editor',staff:'staff-editor',systems:'systems-editor',joinSteps:'join-steps-editor',faqs:'faq-editor',rules:'rules-editor',marketplace:'marketplace-editor',support:'support-editor',ticker:'ticker-editor'};
 function renderEditors(){const s=FSRP_STORE.get();Object.entries(editorIds).forEach(([key,id])=>{const root=document.getElementById(id);if(!root)return;root.innerHTML=(s[key]||[]).map((item,i)=>`<div class="editor-item"><div class="editor-item-head"><strong>${item.name||item.title||item.question||item.text||`${key} ${i+1}`}</strong><button class="btn btn-danger btn-small" data-remove-item="${key}" data-index="${i}">Remove</button></div><div class="field-grid">${schemas[key].map(f=>{let v=item[f];if(Array.isArray(v))v=v.join('\n');if(typeof v==='boolean')return `<div class="field"><label>${f}</label><select data-edit-item="${key}" data-index="${i}" data-field="${f}"><option value="true" ${v?'selected':''}>Enabled</option><option value="false" ${!v?'selected':''}>Disabled</option></select></div>`;return `<div class="field"><label>${f}</label>${['description','body','answer','items'].includes(f)?`<textarea data-edit-item="${key}" data-index="${i}" data-field="${f}">${v??''}</textarea>`:`<input data-edit-item="${key}" data-index="${i}" data-field="${f}" value="${String(v??'').replaceAll('&','&amp;').replaceAll('"','&quot;')}">`}</div>`}).join('')}</div></div>`).join('')})}
 function updateArray(el){const next=clone(FSRP_STORE.get()),k=el.dataset.editItem,i=+el.dataset.index,f=el.dataset.field;let v=el.value;if(v==='true'||v==='false')v=v==='true';if(f==='items')v=v.split('\n').filter(Boolean);next[k][i][f]=v;FSRP_STORE.set(next);renderEditors()}
 async function publish(){if(role==='preview'){toast('Local preview saved in this browser. Sign in to publish to Cloudflare.');return}try{const r=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({settings:FSRP_STORE.get()})});const d=await r.json();if(!r.ok)throw Error(d.error||'Publish failed');document.getElementById('save-state').textContent='Published to Cloudflare.';toast('Website published')}catch(e){toast(e.message)}}

 async function uploadAsset(){const file=document.getElementById('asset-file')?.files?.[0];if(!file)return toast('Choose a file first.');if(role==='preview')return toast('Use Local Preview, or sign in to upload permanently to R2.');const form=new FormData();form.append('file',file);try{const r=await fetch('/api/media',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:form});const d=await r.json();if(!r.ok)throw Error(d.error||'Upload failed');showAsset({label:document.getElementById('asset-label')?.value||file.name,url:d.url,type:file.type});await navigator.clipboard?.writeText(d.url);toast('Uploaded to R2. URL copied.')}catch(e){toast(e.message)}}
 function showAsset(asset){const root=document.getElementById('asset-grid');if(!root)return;const card=document.createElement('article');card.className='asset-card';const isVideo=String(asset.type).startsWith('video/'),isAudio=String(asset.type).startsWith('audio/');card.innerHTML=`${isVideo?`<video controls src="${asset.url}"></video>`:isAudio?`<audio controls src="${asset.url}"></audio>`:`<img src="${asset.url}" alt="${asset.label}">`}<strong>${asset.label}</strong><div class="field"><label>Asset URL</label><input readonly value="${asset.url}"></div><button class="btn btn-ghost btn-small" type="button">Copy URL</button>`;card.querySelector('button').onclick=async()=>{await navigator.clipboard?.writeText(asset.url);toast('Asset URL copied')};root.prepend(card)}
 document.addEventListener('click',e=>{if(e.target.id==='manager-login-btn')login();if(e.target.id==='manager-local-preview-btn')unlock();const tab=e.target.closest('[data-manager-tab]');if(tab){document.querySelectorAll('[data-manager-tab]').forEach(x=>x.classList.toggle('is-active',x===tab));document.querySelectorAll('[data-manager-panel]').forEach(x=>x.classList.toggle('is-active',x.dataset.managerPanel===tab.dataset.managerTab))}const add=e.target.closest('[data-add-item]');if(add){const k=add.dataset.addItem,next=clone(FSRP_STORE.get());next[k]??=[];next[k].push(Object.fromEntries((schemas[k]||['title']).map(f=>[f,f==='enabled'?true:''])));FSRP_STORE.set(next);renderEditors()}const rem=e.target.closest('[data-remove-item]');if(rem){const next=clone(FSRP_STORE.get());next[rem.dataset.removeItem].splice(+rem.dataset.index,1);FSRP_STORE.set(next);renderEditors()}if(e.target.id==='publish-btn')publish();if(e.target.id==='preview-refresh-btn'){bindFields();renderEditors();toast('Preview refreshed')}if(e.target.id==='reset-preview-btn'){FSRP_STORE.reset();bindFields();renderEditors();toast('Preview reset')}if(e.target.id==='asset-local-preview-btn'){const file=document.getElementById('asset-file')?.files?.[0];if(!file){toast('Choose an image, video, or audio file first.')}else{const url=URL.createObjectURL(file);showAsset({label:document.getElementById('asset-label')?.value||file.name,url,type:file.type,local:true});toast('Local asset preview created')}}if(e.target.id==='asset-upload-btn')uploadAsset();if(e.target.id==='export-btn'){const blob=new Blob([JSON.stringify(FSRP_STORE.get(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='FSRP-website-backup.json';a.click();URL.revokeObjectURL(a.href)}if(e.target.id==='status-publish-btn'){const next=clone(FSRP_STORE.get());next.status.updatedAt=new Date().toLocaleString();FSRP_STORE.set(next);bindFields();toast('Status timestamp updated')}});
 document.addEventListener('input',e=>{if(e.target.matches('[data-edit-item]'))updateArray(e.target)});document.addEventListener('change',e=>{if(e.target.matches('[data-edit-item]'))updateArray(e.target);if(e.target.id==='intro-local-file'&&e.target.files[0]){const f=e.target.files[0],url=URL.createObjectURL(f),next=clone(FSRP_STORE.get());next.experience.introMediaType=f.type.startsWith('video/')?'video':'image';next.experience.introMediaUrl=url;FSRP_STORE.set(next);bindFields();toast('Local intro media preview ready')}});document.getElementById('import-file')?.addEventListener('change',async e=>{try{FSRP_STORE.set(JSON.parse(await e.target.files[0].text()));bindFields();renderEditors();toast('Backup imported into preview')}catch{toast('Invalid JSON backup')}})
})();
