# Cloudflare Pages configuration
name = "florida-state-roleplay"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "SITE_SETTINGS"
id = "d5253d8c54c54cb19f08b3bc3b61e90e"
